# Range

In [2]:
range(5) # starting index 0 and end is 5

range(0, 5)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
r = range(5)
r

range(0, 5)

In [5]:
for i in range(5):
    print(i)

0
1
2
3
4


In [6]:
range(10,40)

range(10, 40)

# range can have upto 3 arguments max

In [7]:
range(10,40,5)

range(10, 40, 5)

In [8]:
r1= range(10,40,5)
r1
list(r1)

[10, 15, 20, 25, 30, 35]

In [9]:
for i in r1:
    print(i)

10
15
20
25
30
35


# Numpy library or Numpy packages
# numpy = DSA + Mathematcis + statics function + linear algebra

# numpy store type of data type

In [10]:
# ! pip install numpy
import numpy as np

In [11]:
np.__version__ 

'1.26.4'

In [12]:
import sys
sys.version

'3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]'

# creating arrays

In [13]:
my_list =[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [14]:
type(my_list)

list

# convert list to array

In [15]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [16]:
type(arr)

numpy.ndarray

# it return space value 

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.arange(3.0)

array([0., 1., 2.])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# when 1st argument is greater than 2nd then array is emptyy

In [22]:
np.arange(20,10)

array([], dtype=int32)

In [23]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [24]:
np.arange(30,20)

array([], dtype=int32)

In [25]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [26]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [27]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [28]:
np.arange(10,10)

array([], dtype=int32)

In [29]:
np.arange(10,30,5)

array([10, 15, 20, 25])

# arange function takes 3 argument max

In [30]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

# parameter tunning

In [41]:
np.zeros(3)

array([0., 0., 0.])

# hyperparamter tunning -> changing the argument or paramter to user prefence

# this hyperparameter change to finetune in LLM model

In [42]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [44]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [45]:
zero =np.zeros((3,3),dtype=int)
zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [46]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [48]:
np.ones(3)

array([1., 1., 1.])

In [49]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [50]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [51]:
rand(3,2)

NameError: name 'rand' is not defined

In [52]:
random.rand(3,2)

NameError: name 'random' is not defined

In [54]:
np.random.rand(5)

array([0.79422784, 0.98633499, 0.95864288, 0.61519178, 0.53818581])

In [55]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

# np.random.rand( )  -> genrates random numbers for the user

In [57]:
np.random.rand(2,4)

array([[0.81287974, 0.0929033 , 0.20116254, 0.59125987],
       [0.06180098, 0.44856316, 0.11823134, 0.63603354]])

In [58]:
np.random.rand(2,5)

array([[0.99284554, 0.0874414 , 0.84841398, 0.73455203, 0.50129173],
       [0.22399457, 0.40372616, 0.39847224, 0.95052113, 0.94858948]])

In [59]:
np.random.rand(2,30)

array([[0.25519129, 0.73600177, 0.94779002, 0.3815426 , 0.58059884,
        0.11934781, 0.30011452, 0.10288973, 0.70812223, 0.61270304,
        0.92217009, 0.87978479, 0.71211101, 0.57236275, 0.54914048,
        0.96258232, 0.90394858, 0.88939147, 0.25897791, 0.44903772,
        0.0622597 , 0.29130498, 0.00847376, 0.04368612, 0.94043367,
        0.8724691 , 0.03452414, 0.90787566, 0.71834236, 0.48247817],
       [0.92939498, 0.91157205, 0.95235709, 0.39166516, 0.37595373,
        0.59684284, 0.08384622, 0.71061716, 0.40692699, 0.83738659,
        0.54495455, 0.88243131, 0.63796611, 0.79004244, 0.74881667,
        0.48891912, 0.39698558, 0.71524061, 0.38747994, 0.2837987 ,
        0.47236624, 0.00484674, 0.14068054, 0.82451384, 0.89969146,
        0.30257456, 0.21622856, 0.50197823, 0.1532002 , 0.40343669]])

# np.random.randint() -> gives random interger given between particular range by user

In [61]:
np.random.randint(2,4)

3

In [62]:
np.random.randint(2,20)

19

In [63]:
np.random.randint(0,1)

0

In [65]:
np.random.randint(10,20,5)

array([18, 12, 17, 19, 16])

In [66]:
np.random.randint(-30,10,5)

array([-14,   8, -28, -17,   8])

In [33]:
np.random.randint(20,30,10)

array([22, 21, 26, 23, 29, 26, 24, 26, 23, 29])

In [34]:
np.random.randint(10,40,(10,10))

array([[22, 29, 37, 19, 27, 13, 35, 10, 25, 32],
       [11, 31, 16, 21, 23, 33, 23, 37, 13, 14],
       [17, 14, 33, 30, 17, 31, 24, 34, 29, 30],
       [30, 22, 15, 25, 24, 14, 28, 14, 26, 37],
       [37, 10, 19, 21, 17, 21, 15, 30, 28, 28],
       [22, 22, 28, 33, 14, 30, 32, 11, 20, 31],
       [32, 17, 23, 10, 16, 18, 36, 15, 19, 27],
       [33, 37, 18, 14, 38, 27, 31, 38, 26, 18],
       [32, 30, 30, 32, 11, 35, 20, 35, 17, 29],
       [31, 13, 17, 16, 39, 37, 29, 21, 11, 11]])

In [35]:
np.random.randint(1,100,(12,12))

array([[92, 84, 40, 35, 69, 44, 96, 93, 49, 74, 13, 71],
       [87, 30, 93,  6, 23, 34, 23, 61, 23, 51, 36, 18],
       [11, 97, 47, 71, 89, 69, 61, 87, 52,  2, 18, 57],
       [92, 62, 94, 55, 98, 15, 83, 69, 89, 89, 14, 40],
       [ 8, 73,  4, 29,  4, 74, 95, 53, 67, 96, 26, 76],
       [47, 31, 71, 54, 44, 18, 86, 44, 73, 23, 68, 25],
       [53, 22, 42,  8, 72, 41,  8, 97,  2, 16, 63, 60],
       [ 5, 11, 20, 50, 25, 70, 84, 78, 47, 73, 54, 93],
       [66, 49, 41, 72,  1, 26, 23,  5, 66, 66, 49, 79],
       [24, 27, 29, 75, 81, 95, 10, 80, 74, 56, 39, 27],
       [12, 79, 38, 52, 47, 78, 48, 37, 43, 34, 23, 75],
       [66, 15, 65, 92, 22,  8, 56, 27, 63, 15, 91, 99]])

# 

# reshape function

In [31]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [34]:
b = np.random.randint(10,20,(5,4))
b

array([[15, 16, 16, 16],
       [17, 10, 12, 12],
       [19, 18, 10, 13],
       [14, 15, 14, 18],
       [15, 18, 16, 19]])

In [35]:
type(b)

numpy.ndarray

In [36]:
b

array([[15, 16, 16, 16],
       [17, 10, 12, 12],
       [19, 18, 10, 13],
       [14, 15, 14, 18],
       [15, 18, 16, 19]])

In [37]:
b[:]

array([[15, 16, 16, 16],
       [17, 10, 12, 12],
       [19, 18, 10, 13],
       [14, 15, 14, 18],
       [15, 18, 16, 19]])

In [38]:
b[1:3]

array([[17, 10, 12, 12],
       [19, 18, 10, 13]])

In [39]:
b[1:3]

array([[17, 10, 12, 12],
       [19, 18, 10, 13]])

In [40]:
b[1,-1]

12

In [41]:
b[2:3]

array([[19, 18, 10, 13]])

In [42]:
b[0:-2]  

array([[15, 16, 16, 16],
       [17, 10, 12, 12],
       [19, 18, 10, 13]])

In [43]:
b[0,2]

16

In [44]:
b[-5,-3] 

16

In [45]:
b[-4,2]

12

In [46]:
np.random.randint(10,20,(4,4))

array([[19, 17, 14, 15],
       [19, 18, 15, 15],
       [19, 18, 15, 19],
       [14, 17, 10, 18]])

In [47]:
b[-4,-2]

12

In [48]:
b[-4:2]

array([[17, 10, 12, 12]])

# Operation

In [49]:
a = np.random.randint(10,20,10)
a

array([18, 13, 13, 18, 12, 10, 18, 17, 13, 13])

In [50]:
id(a)

2261727717648

In [51]:
arr

array([0, 1, 2, 3, 4, 5])

In [52]:
arr2 = np.random.randint(0,100,(10,10))

In [53]:
arr2

array([[80, 21, 91,  9, 93, 34, 80, 24, 43, 72],
       [42, 19, 89, 15, 11, 50, 46, 21, 39, 54],
       [30, 65, 24, 50, 60,  6, 56, 72, 15, 93],
       [83, 85,  2, 24, 47, 24, 75, 75,  8, 81],
       [26, 50, 77, 29, 37, 25, 70, 77, 68, 55],
       [40, 65, 42, 31, 26, 73, 17, 88, 67, 55],
       [99, 83, 38,  8, 65, 10,  3, 26, 84, 62],
       [73, 11, 95, 87, 90, 12, 49, 13, 24, 16],
       [12, 69, 65, 98, 25,  0, 48, 31, 76, 38],
       [38, 65, 97, 74, 95, 17, 61, 82, 27, 89]])

In [55]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [56]:
arr[:4] 

array([0, 1, 2, 3])

In [57]:
arr2[:]

array([[80, 21, 91,  9, 93, 34, 80, 24, 43, 72],
       [42, 19, 89, 15, 11, 50, 46, 21, 39, 54],
       [30, 65, 24, 50, 60,  6, 56, 72, 15, 93],
       [83, 85,  2, 24, 47, 24, 75, 75,  8, 81],
       [26, 50, 77, 29, 37, 25, 70, 77, 68, 55],
       [40, 65, 42, 31, 26, 73, 17, 88, 67, 55],
       [99, 83, 38,  8, 65, 10,  3, 26, 84, 62],
       [73, 11, 95, 87, 90, 12, 49, 13, 24, 16],
       [12, 69, 65, 98, 25,  0, 48, 31, 76, 38],
       [38, 65, 97, 74, 95, 17, 61, 82, 27, 89]])

In [58]:
arr2[0:5]

array([[80, 21, 91,  9, 93, 34, 80, 24, 43, 72],
       [42, 19, 89, 15, 11, 50, 46, 21, 39, 54],
       [30, 65, 24, 50, 60,  6, 56, 72, 15, 93],
       [83, 85,  2, 24, 47, 24, 75, 75,  8, 81],
       [26, 50, 77, 29, 37, 25, 70, 77, 68, 55]])

In [59]:
arr2[1,4] 

11

In [60]:
arr2[-5,-5]

73

In [61]:
arr2[-1,-2]

27

In [62]:
arr2[::-1]

array([[38, 65, 97, 74, 95, 17, 61, 82, 27, 89],
       [12, 69, 65, 98, 25,  0, 48, 31, 76, 38],
       [73, 11, 95, 87, 90, 12, 49, 13, 24, 16],
       [99, 83, 38,  8, 65, 10,  3, 26, 84, 62],
       [40, 65, 42, 31, 26, 73, 17, 88, 67, 55],
       [26, 50, 77, 29, 37, 25, 70, 77, 68, 55],
       [83, 85,  2, 24, 47, 24, 75, 75,  8, 81],
       [30, 65, 24, 50, 60,  6, 56, 72, 15, 93],
       [42, 19, 89, 15, 11, 50, 46, 21, 39, 54],
       [80, 21, 91,  9, 93, 34, 80, 24, 43, 72]])

In [63]:
arr2[::-2]

array([[38, 65, 97, 74, 95, 17, 61, 82, 27, 89],
       [73, 11, 95, 87, 90, 12, 49, 13, 24, 16],
       [40, 65, 42, 31, 26, 73, 17, 88, 67, 55],
       [83, 85,  2, 24, 47, 24, 75, 75,  8, 81],
       [42, 19, 89, 15, 11, 50, 46, 21, 39, 54]])

In [64]:
arr2[::-3]

array([[38, 65, 97, 74, 95, 17, 61, 82, 27, 89],
       [99, 83, 38,  8, 65, 10,  3, 26, 84, 62],
       [83, 85,  2, 24, 47, 24, 75, 75,  8, 81],
       [80, 21, 91,  9, 93, 34, 80, 24, 43, 72]])

In [65]:
arr2[:-3]

array([[80, 21, 91,  9, 93, 34, 80, 24, 43, 72],
       [42, 19, 89, 15, 11, 50, 46, 21, 39, 54],
       [30, 65, 24, 50, 60,  6, 56, 72, 15, 93],
       [83, 85,  2, 24, 47, 24, 75, 75,  8, 81],
       [26, 50, 77, 29, 37, 25, 70, 77, 68, 55],
       [40, 65, 42, 31, 26, 73, 17, 88, 67, 55],
       [99, 83, 38,  8, 65, 10,  3, 26, 84, 62]])

In [66]:
arr.max()

5

In [67]:
arr.min()

0

In [68]:
arr.mean()

2.5

In [69]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [70]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

# Without work on * import can you please find the median ,mode

In [71]:
arr

array([0, 1, 2, 3, 4, 5])

In [72]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [73]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [74]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [78]:
arr

array([0, 1, 2, 3, 4, 5])

In [79]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [80]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
arr.reshape(2,3,order='F') # print element with fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [82]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [83]:
arr

array([0, 1, 2, 3, 4, 5])

In [84]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
arr.reshape(1,4) 

ValueError: cannot reshape array of size 6 into shape (1,4)

In [86]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [87]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [88]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [89]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [90]:
arr.reshape(3,2) 

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing

In [91]:
mat = np.arange(0,100).reshape(10,10)

In [92]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
row = 4
col = 5

In [94]:
col

5

In [95]:
row

4

In [96]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [97]:
mat[row,col] 

45

In [98]:
mat[4,5]

45

In [99]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [100]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [101]:
col =6

In [102]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [103]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [104]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [105]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [106]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [108]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [107]:
row

4

In [109]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [110]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [111]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [112]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [113]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [114]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [115]:
mat[1,4]

14

In [116]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [117]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [119]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [120]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [121]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [122]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [123]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [124]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [125]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [126]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [127]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [128]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [129]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [130]:
mat[0,1]

1

In [131]:
mat[1,6]

16

In [132]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [133]:
mat[1:2,2:4] 

array([[12, 13]])

In [134]:
mat[2:3,2:3] 

array([[22]])

In [135]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [136]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [137]:
mat[2:3,4:5]

array([[24]])

# Masking

In [138]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [139]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [140]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [141]:
mat[mat==50]

array([50])

In [142]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [143]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [144]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [145]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [146]:
a4 = mat[mat==50]
a4

array([50])

# PRogram to genrate OTP

In [147]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 4522
