# Range

In [1]:
range(5) # starting index 0 and end is 5

range(0, 5)

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
r = range(5)
r

range(0, 5)

In [4]:
for i in range(5):
    print(i)

0
1
2
3
4


In [5]:
range(10,40)

range(10, 40)

# range can have upto 3 arguments max

In [6]:
range(10,40,5)

range(10, 40, 5)

In [7]:
r1= range(10,40,5)
r1
list(r1)

[10, 15, 20, 25, 30, 35]

In [11]:
for i in r1:
    print(i)

10
15
20
25
30
35


# Numpy library or Numpy packages
# numpy = DSA + Mathematcis + statics function + linear algebra

# numpy store type of data type

In [13]:
import numpy as np

In [14]:
np.__version__ 

'1.26.4'

In [15]:
import sys
sys.version

'3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]'

# creating arrays

In [18]:
my_list =[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [19]:
type(my_list)

list

# convert list to array

In [21]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [22]:
type(arr)

numpy.ndarray

# it return space value 

In [24]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.arange(3.0)

array([0., 1., 2.])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# when 1st argument is greater than 2nd then array is emptyy

In [29]:
np.arange(20,10)

array([], dtype=int32)

In [31]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [30]:
np.arange(30,20)

array([], dtype=int32)

In [32]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [33]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [35]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [37]:
np.arange(10,10)

array([], dtype=int32)

In [39]:
np.arange(10,30,5)

array([10, 15, 20, 25])

# arange function takes 3 argument max

In [40]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

# parameter tunning

In [41]:
np.zeros(3)

array([0., 0., 0.])

# hyperparamter tunning -> changing the argument or paramter to user prefence

# this hyperparameter change to finetune in LLM model

In [42]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [44]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [45]:
zero =np.zeros((3,3),dtype=int)
zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [46]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [48]:
np.ones(3)

array([1., 1., 1.])

In [49]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [50]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [51]:
rand(3,2)

NameError: name 'rand' is not defined

In [52]:
random.rand(3,2)

NameError: name 'random' is not defined

In [54]:
np.random.rand(5)

array([0.79422784, 0.98633499, 0.95864288, 0.61519178, 0.53818581])

In [55]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

# np.random.rand( )  -> genrates random numbers for the user

In [57]:
np.random.rand(2,4)

array([[0.81287974, 0.0929033 , 0.20116254, 0.59125987],
       [0.06180098, 0.44856316, 0.11823134, 0.63603354]])

In [58]:
np.random.rand(2,5)

array([[0.99284554, 0.0874414 , 0.84841398, 0.73455203, 0.50129173],
       [0.22399457, 0.40372616, 0.39847224, 0.95052113, 0.94858948]])

In [59]:
np.random.rand(2,30)

array([[0.25519129, 0.73600177, 0.94779002, 0.3815426 , 0.58059884,
        0.11934781, 0.30011452, 0.10288973, 0.70812223, 0.61270304,
        0.92217009, 0.87978479, 0.71211101, 0.57236275, 0.54914048,
        0.96258232, 0.90394858, 0.88939147, 0.25897791, 0.44903772,
        0.0622597 , 0.29130498, 0.00847376, 0.04368612, 0.94043367,
        0.8724691 , 0.03452414, 0.90787566, 0.71834236, 0.48247817],
       [0.92939498, 0.91157205, 0.95235709, 0.39166516, 0.37595373,
        0.59684284, 0.08384622, 0.71061716, 0.40692699, 0.83738659,
        0.54495455, 0.88243131, 0.63796611, 0.79004244, 0.74881667,
        0.48891912, 0.39698558, 0.71524061, 0.38747994, 0.2837987 ,
        0.47236624, 0.00484674, 0.14068054, 0.82451384, 0.89969146,
        0.30257456, 0.21622856, 0.50197823, 0.1532002 , 0.40343669]])

# np.random.randint() -> gives random interger given between particular range by user

In [61]:
np.random.randint(2,4)

3

In [62]:
np.random.randint(2,20)

19

In [63]:
np.random.randint(0,1)

0

In [65]:
np.random.randint(10,20,5)

array([18, 12, 17, 19, 16])

In [66]:
np.random.randint(-30,10,5)

array([-14,   8, -28, -17,   8])