# creating numpy array

In [1]:
import numpy as np

In [2]:
np.array([2,3,4,6,5,5]) # 1D array

array([2, 3, 4, 6, 5, 5])

In [5]:
a = np.array([1,2,3,4,]) # vector
print(a)

[1 2 3 4]


In [6]:
type(a)

numpy.ndarray

In [9]:
# 2D array (matrix)
new =np.array([[45,34,22,2],[24,55,3,22]])
print(new)

[[45 34 22  2]
 [24 55  3 22]]


In [10]:
# 3D array ----Tensor
np.array([[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

# dtype

In [11]:
np.array([11,23,44],dtype=float)

array([11., 23., 44.])